### PR TITLE
Social media icons + pod data + enhanced UI

### PR DESCRIPTION
**Pull request by ricardoprins**
### Fixes:
#11 and #13 

- Added pod information. **TODO:** Add Yididya info and picture (could not be found anywhere)
- Added pictures for pod members. A .jpeg format was chosen to have reduced size
- Added social media and pictures to cards.
- Added carousel animation to cards, to improve UI and visibility.
- Added pod number to config.yml 
- Added .DS_store to .gitignore (we've noticed that this file was uploaded to the repo in a previous PR)

### CODE REVIEW

**Comment by GustavoElizarraras** [comment]
Hi @gauravdas014, It would be awesome if you could review our PR. Most of the added files are CSS needed to make the carousel effect and social media icons.

**Comment by gauravdas014** [comment]
@GustavoElizarraras LGTM 🚀

**Comment by khattakdev** [comment]
@ricardoprins This looks good

Just remove the photos from the header section.

image

To make it look like:
image

**Comment by ricardoprins** [comment]
Fixed. Also fixed responsiveness in _description.html_ file.

**Review by khattakdev — APPROVED** [review]

**Pull request merged**
