### PR TITLE
(Feat) Add Leaderboard

### PR DESCRIPTION
**Pull request by P0intMaN**
## Please, go through these steps before you submit a PR.

- [x] My Pod Leader knows I'm working on this Pull Request
- [x] I've explained what the Pull Request is adding.
- [x] I've explained why this is important.

Attempts to fix:
- #4

### CODE REVIEW

**Comment by P0intMaN** [comment]
Pinging @rida-hash @GustavoElizarraras for review

**Review by GustavoElizarraras — APPROVED** [review]
Looks good to me, nice API implementation.

**Review by khattakdev — APPROVED** [review]

**Comment by khattakdev** [comment]
@P0intMaN I believe this PR messed up with the map that @Damans227 worked on and it's not showing up after this PR

**Review by Damans227 — COMMENTED** [review]
`{% include podmap.html %}` is missing from index.html. Should be a quick fix, if the file itself has not been removed.

**Comment by Damans227** [comment]
@P0intMaN @khattakdev raised a new PR to fix the issue: https://github.com/MLH-Fellowship/pod-4.1.5-portfolio/pull/26 Ptal, thx!

**Comment by P0intMaN** [comment]
Alright, I'm sorry for screwing up xD. Yes, should've added podmap.html

**Pull request merged**
