### PR TITLE
Added everyone on map, and a few tweaks

### LINKED ISSUE #10: Add a map showing all the countries that fellows are located in
Underneath projects and fellows, have an interactive map that displays where everyone is located.

- [ ] When you click on the pin location for that fellow, it gives you a card with information about the fellow (similar to the fellow section

You can chose to have pins or use circular profile pictures to show where everyone is on the map. You could remove the fellows section and replace it with the map.

### PR DESCRIPTION
**Pull request by Shikhar15606**
## Please, go through these steps before you submit a PR.

- [x] My Pod Leader knows I'm working on this Pull Request
- [x] I've explained what the Pull Request is adding.
- [x] I've explained why this is important.

This Pull Request Fixes #10
@Damans227 @ricardoprins @khattakdev PTAL, thx!

### CODE REVIEW

**Comment by Damans227** [comment]
@Shikhar15606 Looks good. Do you think it's possible to adjust the default zoom level and coordinates to show all the fellows at once ? 

This is what it looks like now: 
Screen Shot 2021-11-12 at 8 14 50 AM

Can we change it to this: 
Screen Shot 2021-11-12 at 8 15 10 AM

**Review by khattakdev — APPROVED** [review]

**Comment by Shikhar15606** [comment]
It would be great @Damans227. Just give me a minute

**Comment by khattakdev** [comment]
> It would be great @Damans227. Just give me a minute

Make another Pull Request for that

**Comment by Shikhar15606** [comment]
I made a new PR for that #25

**Pull request merged**
