### PR TITLE
added stats

### PR DESCRIPTION
**Pull request by esh04**
## Please, go through these steps before you submit a PR.

- [x] My Pod Leader knows I'm working on this Pull Request
- [x] I've explained what the Pull Request is adding.
- [x] I've explained why this is important.

### CODE REVIEW

**Comment by esh04** [comment]
@khattakdev Made a new PR after pulling, please merge this one.

**Comment by P0intMaN** [comment]
Attempts to fix:
- #4

**Review by GustavoElizarraras — APPROVED** [review]
LGTM!

**Review by P0intMaN — APPROVED** [review]
GTG

**Review by khattakdev — APPROVED** [review]

**Pull request merged**
