### PR TITLE
🐛 Bug Fix : Improved  profile picture layout

### LINKED ISSUE #12: Improve profile picture layout
At the moment, the profile pictures at the top, overflow when the screen is too narrow, or there's too many pictures!

This issue will need you to go through the CSS and make sure the website is responsive!

Screenshot 2021-09-30 at 14 21 19
Screenshot 2021-09-30 at 14 21 58

### PR DESCRIPTION
**Pull request by kalyanchirla**
## Please, go through these steps before you submit a PR.

- [X] My Pod Leader knows I'm working on this Pull Request
- [X] I've explained what the Pull Request is adding.
- [X] I've explained why this is important.

Resolve #12

### CODE REVIEW

**Comment by khattakdev** [comment]
@Damans227 Please review this

**Comment by Damans227** [comment]
> @Damans227 Please review this

Will do this today. Thx!

**Review by Damans227 — APPROVED** [review]
LGTM @khattakdev

**Comment by MaheraFurniturewala** [comment]
@sumitshinde2608 Could you please review this request?

**Review by sumitshinde2608 — APPROVED** [review]

**Comment by sumitshinde2608** [comment]
@MaheraFurniturewala @kalyanchirla  I have approved the changes, it's safe to merge. It's better you resolve the branch conflicts because @khattakdev is going to ask you to do the same sooner or later :p.

**Comment by kalyanchirla** [comment]
Resolved the merged conflicts. Please review @khattakdev

**Comment by khattakdev** [comment]
@kalyanchirla What does this PR do?

**Comment by kalyanchirla** [comment]
@khattakdev This PR is regarding the issue #12. The issue is to make the profile pictures responsive without overlapping with the text. I guess there is no issue #12 now because of the changes made.

**Pull request closed without merging**
