### PR TITLE
Added stats of PRs

### PR DESCRIPTION
**Pull request by esh04**
## Please, go through these steps before you submit a PR.

- [x] My Pod Leader knows I'm working on this Pull Request
- [x] I've explained what the Pull Request is adding.
- [x] I've explained why this is important.

### CODE REVIEW

**Comment by esh04** [comment]
@rida-hash @kalyanchirla could you please review?

**Review by kalyanchirla — COMMENTED** [review]
I have reviewed the PR. The issue describes to display the number of contributions between people. If I'm wrong, it should display something like this: (a leaderboard)
| Fellow Name     | PR's merged |
| ----------- | ----------- |
| Name 1     | 2       |
| Name 2  | 0        |

or may be some other way which shows individual contributions between fellows. Your code change is displaying the stats in a more general way showing only the total number of PR's:

**Comment by esh04** [comment]
@kalyanchirla The leaderboard portion is being covered in @P0intMaN 's code. 
image

The code in this pull request is just some additional info

**Comment by kalyanchirla** [comment]
Ok. Then this should be good.

**Review by kalyanchirla — APPROVED** [review]

**Comment by khattakdev** [comment]
@esh04 can you please fix this?
image

The Netlify actions are failing

**Comment by esh04** [comment]
yeah, i made a mistake while resolving conflicts ill just get rid of my last commit.
________________________________

**Comment by khattakdev** [comment]
@esh04 
The PR deletes all the changes of other fellows. 
Either fix that in this issue or close this one and make a new one as changes are alot.

**Pull request closed without merging**
